### PR TITLE
Fix graph parse

### LINKED ISSUE #11: Bug: SPARQL Update not capturing Subjects for SNS Message
Sparql Update message is below.

This is using Python's rdflib to create the SPARQL request. The triples are added to Neptune.

```
INSERT { <http://sul.stanford.edu/rialto/context/positions/capFaculty_Bio-ABC_3784> <http://vivoweb.org/ontology/core#hrJobTitle> "George A. Zimmermann Professor and Professor of Pediatrics" .
                <http://sul.stanford.edu/rialto/agents/orgs/Child_Health_Research_Institute> <http://vivoweb.org/ontology/core#relatedBy> <http://sul.stanford.edu/rialto/context/positions/capFaculty_Child_Health_Research_Institute_3784> .
                <http://sul.stanford.edu/rialto/context/positions/capFaculty_Stanford_Neurosciences_Institute_3784> <http://vivoweb.org/ontology/core#relates> <http://sul.stanford.edu/rialto/agents/people/3784> .
                <http://sul.stanford.edu/rialto/agents/people/3784> <http://vivoweb.org/ontology/core#relatedBy> <http://sul.stanford.edu/rialto/context/relationships/75872_3784> .
                <http://sul.stanford.edu/rialto/context/names/75872> <http://www.w3.org/2006/vcard/ns#given-name> "Noga" .
                <http://sul.stanford.edu/rialto/agents/people/3784> <http://vivoweb.org/ontology/core#hasResearchArea> <http://sul.stanford.edu/rialto/concepts/autoimmunity%2C_neuroimmunology%2C_immunology%2C_multiple_sclerosis%2C_Neurobiology%2C_Neuroscience%2C_Translational_Medicine%2C_Molecular_Medicine_%26_Human_Disease%2C_Immunology> .
                <http://sul.stanford.edu/rialto/agents/people/3784> <http://vivoweb.org/ontology/core#overview> "My research is in neuroimmunology. I attend on the inpatient service at LPCH." .
                <http://sul.stanford.edu/rialto/context/positions/capFaculty_Pediatrics_3784> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://vivoweb.org/ontology/core#Position> .
                <http://sul.stanford.edu/rialto/context/roles/AdvisorRole> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://vivoweb.org/ontology/core#AdvisorRole> .
                <http://sul.stanford.edu/rialto/agents/people/75872> <http://purl.obolibrary.org/obo/RO_0000053> <http://sul.stanford.edu/rialto/context/roles/AdviseeRole> .
                <http://sul.stanford.edu/rialto/concepts/autoimmunity%2C_neuroimmunology%2C_immunology%2C_multiple_sclerosis%2C_Neurobiology%2C_Neuroscience%2C_Translational_Medicine%2C_Molecular_Medicine_%26_Human_Disease%2C_Immunology> <http://www.w3.org/2000/01/rdf-schema#label> "autoimmunity%2C_neuroimmunology%2C_immunology%2C_multiple_sclerosis%2C_Neurobiology%2C_Neuroscience%2C_Translational_Medicine%2C_Molecular_Medicine_%26_Human_Disease%2C_Immunology" .
                <http://sul.stanford.edu/rialto/agents/people/3784> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://vivoweb.org/ontology/core#FacultyMember> .
                <http://sul.stanford.edu/rialto/context/positions/capFaculty_NULL_3784> <http://purl.org/dc/terms/date> "unknown/2018-08" .
                <http://sul.stanford.edu/rialto/context/positions/capFaculty_NULL_3784> <http://www.w3.org/2000/01/rdf-schema#label> "capFaculty" .
                <http://sul.stanford.edu/rialto/context/positions/capFaculty_Stanford_Neurosciences_Institute_3784> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://vivoweb.org/ontology/core#Position> .
                <http://sul.stanford.edu/rialto/context/positions/capFaculty_Child_Health_Research_Institute_3784> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://vivoweb.org/ontology/core#Position> .
                <http://sul.stanford.edu/rialto/context/relationships/75872_3784> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://vivoweb.org/ontology/core#AdvisingRelationship> .
                <http://sul.stanford.edu/rialto/context/positions/capFaculty_Stanford_Neurosciences_Institute_3784> <http://purl.org/dc/terms/date> "unknown/2018-08" .
                <http://sul.stanford.edu/rialto/context/positions/capFaculty_Stanford_Neurosciences_Institute_3784> <http://www.w3.org/2000/01/rdf-schema#label> "capFaculty" .
                <http://sul.stanford.edu/rialto/context/positions/capFaculty_Pediatrics_3784> <http://www.w3.org/2000/01/rdf-schema#label> "capFaculty" .
                <http://sul.stanford.edu/rialto/context/positions/capFaculty_Pediatrics_3784> <http://vivoweb.org/ontology/core#relates> <http://sul.stanford.edu/rialto/agents/people/3784> .
                <http://sul.stanford.edu/rialto/agents/people/75872> <http://vivoweb.org/ontology/core#relatedBy> <http://sul.stanford.edu/rialto/context/relationships/75872_3784> .
                <http://sul.stanford.edu/rialto/context/positions/capFaculty_Bio-X_3784> <http://vivoweb.org/ontology/core#relates> <http://sul.stanford.edu/rialto/agents/orgs/Bio-X> .
                <http://sul.stanford.edu/rialto/agents/people/3784> <http://vivoweb.org/ontology/core#relatedBy> <http://sul.stanford.edu/rialto/context/positions/capFaculty_Bio-X_3784> .
                <http://sul.stanford.edu/rialto/agents/orgs/Pediatrics> <http://vivoweb.org/ontology/core#relatedBy> <http://sul.stanford.edu/rialto/context/positions/capFaculty_Pediatrics_3784> .
                <http://sul.stanford.edu/rialto/context/positions/capFaculty_Neurology_3784> <http://vivoweb.org/ontology/core#relates> <http://sul.stanford.edu/rialto/agents/people/3784> .
                <http://sul.stanford.edu/rialto/context/positions/capFaculty_Bio-X_3784> <http://www.w3.org/2000/01/rdf-schema#label> "capFaculty" .
                <http://sul.stanford.edu/rialto/agents/people/3784> <http://vivoweb.org/ontology/core#relatedBy> <http://sul.stanford.edu/rialto/context/positions/capFaculty_NULL_3784> .
                <http://sul.stanford.edu/rialto/context/positions/capFaculty_Pediatrics_3784> <http://vivoweb.org/ontology/core#relates> <http://sul.stanford.edu/rialto/agents/orgs/Pediatrics> .
                <http://sul.stanford.edu/rialto/context/positions/capFaculty_Neurology_3784> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://vivoweb.org/ontology/core#Position> .
                <http://sul.stanford.edu/rialto/context/names/75872> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/2006/vcard/ns#Name> .
                <http://sul.stanford.edu/rialto/agents/people/3784> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://xmlns.com/foaf/0.1/Person> .
                <http://sul.stanford.edu/rialto/context/names/75872> <http://www.w3.org/2006/vcard/ns#family-name> "Or-Geva" .
                <http://sul.stanford.edu/rialto/context/roles/AdviseeRole> <http://purl.obolibrary.org/obo/RO_0000052> <http://sul.stanford.edu/rialto/agents/people/75872> .
                <http://sul.stanford.edu/rialto/agents/people/3784> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://xmlns.com/foaf/0.1/Agent> .
                <http://sul.stanford.edu/rialto/agents/people/75872> <http://www.w3.org/2006/vcard/ns#hasName> <http://sul.stanford.edu/rialto/context/names/75872> .
                <http://sul.stanford.edu/rialto/context/positions/capFaculty_Bio-X_3784> <http://purl.org/dc/terms/date> "unknown/2018-08" .
                <http://sul.stanford.edu/rialto/context/positions/capFaculty_Stanford_Neurosciences_Institute_3784> <http://vivoweb.org/ontology/core#relates> <http://sul.stanford.edu/rialto/agents/orgs/Stanford_Neurosciences_Institute> .
                <http://sul.stanford.edu/rialto/context/positions/capFaculty_Pediatrics_3784> <http://vivoweb.org/ontology/core#hrJobTitle> "George A. Zimmermann Professor and Professor of Pediatrics" .
                <http://sul.stanford.edu/rialto/context/positions/capFaculty_NULL_3784> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://vivoweb.org/ontology/core#Position> .
                <http://sul.stanford.edu/rialto/context/positions/capFaculty_NULL_3784> <http://vivoweb.org/ontology/core#hrJobTitle> "George A. Zimmermann Professor and Professor of Pediatrics" .
                <http://sul.stanford.edu/rialto/agents/orgs/Bio-X> <http://vivoweb.org/ontology/core#relatedBy> <http://sul.stanford.edu/rialto/context/positions/capFaculty_Bio-X_3784> .
                <http://sul.stanford.edu/rialto/context/positions/capFaculty_Child_Health_Research_Institute_3784> <http://vivoweb.org/ontology/core#relates> <http://sul.stanford.edu/rialto/agents/orgs/Child_Health_Research_Institute> .
                <http://sul.stanford.edu/rialto/agents/orgs/Stanford_Neurosciences_Institute> <http://vivoweb.org/ontology/core#relatedBy> <http://sul.stanford.edu/rialto/context/positions/capFaculty_Stanford_Neurosciences_Institute_3784> .
                <http://sul.stanford.edu/rialto/agents/people/3784> <http://vivoweb.org/ontology/core#relatedBy> <http://sul.stanford.edu/rialto/context/positions/capFaculty_Neurology_3784> .
                <http://sul.stanford.edu/rialto/context/relationships/75872_3784> <http://vivoweb.org/ontology/core#relates> <http://sul.stanford.edu/rialto/agents/people/75872> .
                <http://sul.stanford.edu/rialto/context/relationships/75872_3784> <http://vivoweb.org/ontology/core#relates> <http://sul.stanford.edu/rialto/agents/people/3784> .
                <http://sul.stanford.edu/rialto/context/positions/capFaculty_Child_Health_Research_Institute_3784> <http://vivoweb.org/ontology/core#relates> <http://sul.stanford.edu/rialto/agents/people/3784> .
                <http://sul.stanford.edu/rialto/context/positions/capFaculty_Neurology_3784> <http://www.w3.org/2000/01/rdf-schema#label> "capFaculty" .
                <http://sul.stanford.edu/rialto/context/positions/capFaculty_NULL_3784> <http://vivoweb.org/ontology/core#relates> <http://sul.stanford.edu/rialto/agents/people/3784> .
                <http://sul.stanford.edu/rialto/context/positions/capFaculty_Child_Health_Research_Institute_3784> <http://www.w3.org/2000/01/rdf-schema#label> "capFaculty" .
                <http://sul.stanford.edu/rialto/context/roles/AdviseeRole> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://vivoweb.org/ontology/core#AdviseeRole> .
                <http://sul.stanford.edu/rialto/agents/people/75872> <http://www.w3.org/2006/vcard/ns#fn> "Noga Or-Geva" .
                <http://sul.stanford.edu/rialto/context/roles/AdvisorRole> <http://purl.obolibrary.org/obo/RO_0000052> <http://sul.stanford.edu/rialto/agents/people/3784> .
                <http://sul.stanford.edu/rialto/context/positions/capFaculty_Bio-X_3784> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://vivoweb.org/ontology/core#Position> .
                <http://sul.stanford.edu/rialto/context/positions/capFaculty_NULL_3784> <http://vivoweb.org/ontology/core#relates> <http://sul.stanford.edu/rialto/agents/orgs/NULL> .
                <http://sul.stanford.edu/rialto/agents/orgs/NULL> <http://vivoweb.org/ontology/core#relatedBy> <http://sul.stanford.edu/rialto/context/positions/capFaculty_NULL_3784> .
                <http://sul.stanford.edu/rialto/agents/people/3784> <http://www.w3.org/2006/vcard/ns#hasEmail> "steinman@stanford.edu" .
                <http://sul.stanford.edu/rialto/agents/people/75872> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://xmlns.com/foaf/0.1/Agent> .
                <http://sul.stanford.edu/rialto/agents/orgs/Neurology> <http://vivoweb.org/ontology/core#relatedBy> <http://sul.stanford.edu/rialto/context/positions/capFaculty_Neurology_3784> .
                <http://sul.stanford.edu/rialto/agents/people/3784> <http://purl.obolibrary.org/obo/RO_0000053> <http://sul.stanford.edu/rialto/context/roles/AdvisorRole> .
                <http://sul.stanford.edu/rialto/context/positions/capFaculty_Neurology_3784> <http://purl.org/dc/terms/date> "unknown/2018-08" .
                <http://sul.stanford.edu/rialto/context/positions/capFaculty_Stanford_Neurosciences_Institute_3784> <http://vivoweb.org/ontology/core#hrJobTitle> "George A. Zimmermann Professor and Professor of Pediatrics" .
                <http://sul.stanford.edu/rialto/agents/people/3784> <http://vivoweb.org/ontology/core#relatedBy> <http://sul.stanford.edu/rialto/context/positions/capFaculty_Child_Health_Research_Institute_3784> .
                <http://sul.stanford.edu/rialto/context/positions/capFaculty_Bio-X_3784> <http://vivoweb.org/ontology/core#relates> <http://sul.stanford.edu/rialto/agents/people/3784> .
                <http://sul.stanford.edu/rialto/context/positions/capFaculty_Neurology_3784> <http://vivoweb.org/ontology/core#relates> <http://sul.stanford.edu/rialto/agents/orgs/Neurology> .
                <http://sul.stanford.edu/rialto/agents/people/3784> <http://vivoweb.org/ontology/core#relatedBy> <http://sul.stanford.edu/rialto/context/positions/capFaculty_Pediatrics_3784> .
                <http://sul.stanford.edu/rialto/agents/people/3784> <http://vivoweb.org/ontology/core#relatedBy> <http://sul.stanford.edu/rialto/context/positions/capFaculty_Stanford_Neurosciences_Institute_3784> .
                <http://sul.stanford.edu/rialto/context/positions/capFaculty_Neurology_3784> <http://vivoweb.org/ontology/core#hrJobTitle> "George A. Zimmermann Professor and Professor of Pediatrics" .
                <http://sul.stanford.edu/rialto/agents/people/75872> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://xmlns.com/foaf/0.1/Person> .
                <http://sul.stanford.edu/rialto/context/positions/capFaculty_Pediatrics_3784> <http://purl.org/dc/terms/date> "unknown/2018-08" .
                <http://sul.stanford.edu/rialto/agents/people/3784> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://vivoweb.org/ontology/core#NonAcademic> .
                <http://sul.stanford.edu/rialto/context/positions/capFaculty_Child_Health_Research_Institute_3784> <http://purl.org/dc/terms/date> "unknown/2018-08" .
                <http://sul.stanford.edu/rialto/concepts/autoimmunity%2C_neuroimmunology%2C_immunology%2C_multiple_sclerosis%2C_Neurobiology%2C_Neuroscience%2C_Translational_Medicine%2C_Molecular_Medicine_%26_Human_Disease%2C_Immunology> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/2004/02/skos/core#Concept> .
                <http://sul.stanford.edu/rialto/context/positions/capFaculty_Child_Health_Research_Institute_3784> <http://vivoweb.org/ontology/core#hrJobTitle> "George A. Zimmermann Professor and Professor of Pediatrics" . }
       WHERE {  }
```

The response in the Cloudwatch logs:
```
16:41:08 START RequestId: b0d8329c-9c2d-11e8-a1ea-d7abd3a0d7fb Version: $LATEST
16:41:08 2018/08/09 23:41:08 BEFORE NEPTUNE: {0xc4200be780}
16:41:09 2018/08/09 23:41:09 AFTER NEPTUNE: [
16:41:09 {
16:41:09 "type" : "UpdateEvent",
16:41:09 "totalElapsedMillis" : 18,
16:41:09 "elapsedMillis" : 17,
16:41:09 "connFlush" : 0,
16:41:09 "batchResolve" : 0,
16:41:09 "whereClause" : 14,
16:41:09 "deleteClause" : 0,
16:41:09 "insertClause" : 2
16:41:09 },
16:41:09 {
16:41:09 "type" : "Commit",
16:41:09 "totalElapsedMillis" : 26
16:41:09 }
16:41:09 ]
16:41:10 2018/08/09 23:41:10 SENDING MESSAGE: {Parts:[] Prefixes:map[]}
16:41:10 END RequestId: b0d8329c-9c2d-11e8-a1ea-d7abd3a0d7fb
16:41:10 REPORT RequestId: b0d8329c-9c2d-11e8-a1ea-d7abd3a0d7fb	Duration: 1382.83 ms	Billed Duration: 1400 ms Memory Size: 128 MB	Max Memory Used: 36 MB
```

### LINKED ISSUE #12: Bug: SPARQL Update with Named Graph is not Registering Subjects at all
See the SPARQL Update message below.

This is using Python's rdflib to generate the SPARQL request.

```
INSERT { GRAPH <http://sul.stanford.edu/rialto/sources/test2> { <http://sul.stanford.edu/rialto/context/positions/capFaculty_Bio-ABC_3784> <http://vivoweb.org/ontology/core#hrJobTitle> "George A. Zimmermann Professor and Professor of Pediatrics" .
                <http://sul.stanford.edu/rialto/agents/orgs/Child_Health_Research_Institute> <http://vivoweb.org/ontology/core#relatedBy> <http://sul.stanford.edu/rialto/context/positions/capFaculty_Child_Health_Research_Institute_3784> .
                <http://sul.stanford.edu/rialto/context/positions/capFaculty_Stanford_Neurosciences_Institute_3784> <http://vivoweb.org/ontology/core#relates> <http://sul.stanford.edu/rialto/agents/people/3784> .
                <http://sul.stanford.edu/rialto/agents/people/3784> <http://vivoweb.org/ontology/core#relatedBy> <http://sul.stanford.edu/rialto/context/relationships/75872_3784> .
                <http://sul.stanford.edu/rialto/context/names/75872> <http://www.w3.org/2006/vcard/ns#given-name> "Noga" .
                <http://sul.stanford.edu/rialto/agents/people/3784> <http://vivoweb.org/ontology/core#hasResearchArea> <http://sul.stanford.edu/rialto/concepts/autoimmunity%2C_neuroimmunology%2C_immunology%2C_multiple_sclerosis%2C_Neurobiology%2C_Neuroscience%2C_Translational_Medicine%2C_Molecular_Medicine_%26_Human_Disease%2C_Immunology> .
                <http://sul.stanford.edu/rialto/agents/people/3784> <http://vivoweb.org/ontology/core#overview> "My research is in neuroimmunology. I attend on the inpatient service at LPCH." .
                <http://sul.stanford.edu/rialto/context/positions/capFaculty_Pediatrics_3784> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://vivoweb.org/ontology/core#Position> .
                <http://sul.stanford.edu/rialto/context/roles/AdvisorRole> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://vivoweb.org/ontology/core#AdvisorRole> .
                <http://sul.stanford.edu/rialto/agents/people/75872> <http://purl.obolibrary.org/obo/RO_0000053> <http://sul.stanford.edu/rialto/context/roles/AdviseeRole> .
                <http://sul.stanford.edu/rialto/concepts/autoimmunity%2C_neuroimmunology%2C_immunology%2C_multiple_sclerosis%2C_Neurobiology%2C_Neuroscience%2C_Translational_Medicine%2C_Molecular_Medicine_%26_Human_Disease%2C_Immunology> <http://www.w3.org/2000/01/rdf-schema#label> "autoimmunity%2C_neuroimmunology%2C_immunology%2C_multiple_sclerosis%2C_Neurobiology%2C_Neuroscience%2C_Translational_Medicine%2C_Molecular_Medicine_%26_Human_Disease%2C_Immunology" .
                <http://sul.stanford.edu/rialto/agents/people/3784> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://vivoweb.org/ontology/core#FacultyMember> .
                <http://sul.stanford.edu/rialto/context/positions/capFaculty_NULL_3784> <http://purl.org/dc/terms/date> "unknown/2018-08" .
                <http://sul.stanford.edu/rialto/context/positions/capFaculty_NULL_3784> <http://www.w3.org/2000/01/rdf-schema#label> "capFaculty" .
                <http://sul.stanford.edu/rialto/context/positions/capFaculty_Stanford_Neurosciences_Institute_3784> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://vivoweb.org/ontology/core#Position> .
                <http://sul.stanford.edu/rialto/context/positions/capFaculty_Child_Health_Research_Institute_3784> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://vivoweb.org/ontology/core#Position> .
                <http://sul.stanford.edu/rialto/context/relationships/75872_3784> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://vivoweb.org/ontology/core#AdvisingRelationship> .
                <http://sul.stanford.edu/rialto/context/positions/capFaculty_Stanford_Neurosciences_Institute_3784> <http://purl.org/dc/terms/date> "unknown/2018-08" .
                <http://sul.stanford.edu/rialto/context/positions/capFaculty_Stanford_Neurosciences_Institute_3784> <http://www.w3.org/2000/01/rdf-schema#label> "capFaculty" .
                <http://sul.stanford.edu/rialto/context/positions/capFaculty_Pediatrics_3784> <http://www.w3.org/2000/01/rdf-schema#label> "capFaculty" .
                <http://sul.stanford.edu/rialto/context/positions/capFaculty_Pediatrics_3784> <http://vivoweb.org/ontology/core#relates> <http://sul.stanford.edu/rialto/agents/people/3784> .
                <http://sul.stanford.edu/rialto/agents/people/75872> <http://vivoweb.org/ontology/core#relatedBy> <http://sul.stanford.edu/rialto/context/relationships/75872_3784> .
                <http://sul.stanford.edu/rialto/context/positions/capFaculty_Bio-X_3784> <http://vivoweb.org/ontology/core#relates> <http://sul.stanford.edu/rialto/agents/orgs/Bio-X> .
                <http://sul.stanford.edu/rialto/agents/people/3784> <http://vivoweb.org/ontology/core#relatedBy> <http://sul.stanford.edu/rialto/context/positions/capFaculty_Bio-X_3784> .
                <http://sul.stanford.edu/rialto/agents/orgs/Pediatrics> <http://vivoweb.org/ontology/core#relatedBy> <http://sul.stanford.edu/rialto/context/positions/capFaculty_Pediatrics_3784> .
                <http://sul.stanford.edu/rialto/context/positions/capFaculty_Neurology_3784> <http://vivoweb.org/ontology/core#relates> <http://sul.stanford.edu/rialto/agents/people/3784> .
                <http://sul.stanford.edu/rialto/context/positions/capFaculty_Bio-X_3784> <http://www.w3.org/2000/01/rdf-schema#label> "capFaculty" .
                <http://sul.stanford.edu/rialto/agents/people/3784> <http://vivoweb.org/ontology/core#relatedBy> <http://sul.stanford.edu/rialto/context/positions/capFaculty_NULL_3784> .
                <http://sul.stanford.edu/rialto/context/positions/capFaculty_Pediatrics_3784> <http://vivoweb.org/ontology/core#relates> <http://sul.stanford.edu/rialto/agents/orgs/Pediatrics> .
                <http://sul.stanford.edu/rialto/context/positions/capFaculty_Neurology_3784> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://vivoweb.org/ontology/core#Position> .
                <http://sul.stanford.edu/rialto/context/names/75872> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/2006/vcard/ns#Name> .
                <http://sul.stanford.edu/rialto/agents/people/3784> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://xmlns.com/foaf/0.1/Person> .
                <http://sul.stanford.edu/rialto/context/names/75872> <http://www.w3.org/2006/vcard/ns#family-name> "Or-Geva" .
                <http://sul.stanford.edu/rialto/context/roles/AdviseeRole> <http://purl.obolibrary.org/obo/RO_0000052> <http://sul.stanford.edu/rialto/agents/people/75872> .
                <http://sul.stanford.edu/rialto/agents/people/3784> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://xmlns.com/foaf/0.1/Agent> .
                <http://sul.stanford.edu/rialto/agents/people/75872> <http://www.w3.org/2006/vcard/ns#hasName> <http://sul.stanford.edu/rialto/context/names/75872> .
                <http://sul.stanford.edu/rialto/context/positions/capFaculty_Bio-X_3784> <http://purl.org/dc/terms/date> "unknown/2018-08" .
                <http://sul.stanford.edu/rialto/context/positions/capFaculty_Stanford_Neurosciences_Institute_3784> <http://vivoweb.org/ontology/core#relates> <http://sul.stanford.edu/rialto/agents/orgs/Stanford_Neurosciences_Institute> .
                <http://sul.stanford.edu/rialto/context/positions/capFaculty_Pediatrics_3784> <http://vivoweb.org/ontology/core#hrJobTitle> "George A. Zimmermann Professor and Professor of Pediatrics" .
                <http://sul.stanford.edu/rialto/context/positions/capFaculty_NULL_3784> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://vivoweb.org/ontology/core#Position> .
                <http://sul.stanford.edu/rialto/context/positions/capFaculty_NULL_3784> <http://vivoweb.org/ontology/core#hrJobTitle> "George A. Zimmermann Professor and Professor of Pediatrics" .
                <http://sul.stanford.edu/rialto/agents/orgs/Bio-X> <http://vivoweb.org/ontology/core#relatedBy> <http://sul.stanford.edu/rialto/context/positions/capFaculty_Bio-X_3784> .
                <http://sul.stanford.edu/rialto/context/positions/capFaculty_Child_Health_Research_Institute_3784> <http://vivoweb.org/ontology/core#relates> <http://sul.stanford.edu/rialto/agents/orgs/Child_Health_Research_Institute> .
                <http://sul.stanford.edu/rialto/agents/orgs/Stanford_Neurosciences_Institute> <http://vivoweb.org/ontology/core#relatedBy> <http://sul.stanford.edu/rialto/context/positions/capFaculty_Stanford_Neurosciences_Institute_3784> .
                <http://sul.stanford.edu/rialto/agents/people/3784> <http://vivoweb.org/ontology/core#relatedBy> <http://sul.stanford.edu/rialto/context/positions/capFaculty_Neurology_3784> .
                <http://sul.stanford.edu/rialto/context/relationships/75872_3784> <http://vivoweb.org/ontology/core#relates> <http://sul.stanford.edu/rialto/agents/people/75872> .
                <http://sul.stanford.edu/rialto/context/relationships/75872_3784> <http://vivoweb.org/ontology/core#relates> <http://sul.stanford.edu/rialto/agents/people/3784> .
                <http://sul.stanford.edu/rialto/context/positions/capFaculty_Child_Health_Research_Institute_3784> <http://vivoweb.org/ontology/core#relates> <http://sul.stanford.edu/rialto/agents/people/3784> .
                <http://sul.stanford.edu/rialto/context/positions/capFaculty_Neurology_3784> <http://www.w3.org/2000/01/rdf-schema#label> "capFaculty" .
                <http://sul.stanford.edu/rialto/context/positions/capFaculty_NULL_3784> <http://vivoweb.org/ontology/core#relates> <http://sul.stanford.edu/rialto/agents/people/3784> .
                <http://sul.stanford.edu/rialto/context/positions/capFaculty_Child_Health_Research_Institute_3784> <http://www.w3.org/2000/01/rdf-schema#label> "capFaculty" .
                <http://sul.stanford.edu/rialto/context/roles/AdviseeRole> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://vivoweb.org/ontology/core#AdviseeRole> .
                <http://sul.stanford.edu/rialto/agents/people/75872> <http://www.w3.org/2006/vcard/ns#fn> "Noga Or-Geva" .
                <http://sul.stanford.edu/rialto/context/roles/AdvisorRole> <http://purl.obolibrary.org/obo/RO_0000052> <http://sul.stanford.edu/rialto/agents/people/3784> .
                <http://sul.stanford.edu/rialto/context/positions/capFaculty_Bio-X_3784> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://vivoweb.org/ontology/core#Position> .
                <http://sul.stanford.edu/rialto/context/positions/capFaculty_NULL_3784> <http://vivoweb.org/ontology/core#relates> <http://sul.stanford.edu/rialto/agents/orgs/NULL> .
                <http://sul.stanford.edu/rialto/agents/orgs/NULL> <http://vivoweb.org/ontology/core#relatedBy> <http://sul.stanford.edu/rialto/context/positions/capFaculty_NULL_3784> .
                <http://sul.stanford.edu/rialto/agents/people/3784> <http://www.w3.org/2006/vcard/ns#hasEmail> "steinman@stanford.edu" .
                <http://sul.stanford.edu/rialto/agents/people/75872> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://xmlns.com/foaf/0.1/Agent> .
                <http://sul.stanford.edu/rialto/agents/orgs/Neurology> <http://vivoweb.org/ontology/core#relatedBy> <http://sul.stanford.edu/rialto/context/positions/capFaculty_Neurology_3784> .
                <http://sul.stanford.edu/rialto/agents/people/3784> <http://purl.obolibrary.org/obo/RO_0000053> <http://sul.stanford.edu/rialto/context/roles/AdvisorRole> .
                <http://sul.stanford.edu/rialto/context/positions/capFaculty_Neurology_3784> <http://purl.org/dc/terms/date> "unknown/2018-08" .
                <http://sul.stanford.edu/rialto/context/positions/capFaculty_Stanford_Neurosciences_Institute_3784> <http://vivoweb.org/ontology/core#hrJobTitle> "George A. Zimmermann Professor and Professor of Pediatrics" .
                <http://sul.stanford.edu/rialto/agents/people/3784> <http://vivoweb.org/ontology/core#relatedBy> <http://sul.stanford.edu/rialto/context/positions/capFaculty_Child_Health_Research_Institute_3784> .
                <http://sul.stanford.edu/rialto/context/positions/capFaculty_Bio-X_3784> <http://vivoweb.org/ontology/core#relates> <http://sul.stanford.edu/rialto/agents/people/3784> .
                <http://sul.stanford.edu/rialto/context/positions/capFaculty_Neurology_3784> <http://vivoweb.org/ontology/core#relates> <http://sul.stanford.edu/rialto/agents/orgs/Neurology> .
                <http://sul.stanford.edu/rialto/agents/people/3784> <http://vivoweb.org/ontology/core#relatedBy> <http://sul.stanford.edu/rialto/context/positions/capFaculty_Pediatrics_3784> .
                <http://sul.stanford.edu/rialto/agents/people/3784> <http://vivoweb.org/ontology/core#relatedBy> <http://sul.stanford.edu/rialto/context/positions/capFaculty_Stanford_Neurosciences_Institute_3784> .
                <http://sul.stanford.edu/rialto/context/positions/capFaculty_Neurology_3784> <http://vivoweb.org/ontology/core#hrJobTitle> "George A. Zimmermann Professor and Professor of Pediatrics" .
                <http://sul.stanford.edu/rialto/agents/people/75872> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://xmlns.com/foaf/0.1/Person> .
                <http://sul.stanford.edu/rialto/context/positions/capFaculty_Pediatrics_3784> <http://purl.org/dc/terms/date> "unknown/2018-08" .
                <http://sul.stanford.edu/rialto/agents/people/3784> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://vivoweb.org/ontology/core#NonAcademic> .
                <http://sul.stanford.edu/rialto/context/positions/capFaculty_Child_Health_Research_Institute_3784> <http://purl.org/dc/terms/date> "unknown/2018-08" .
                <http://sul.stanford.edu/rialto/concepts/autoimmunity%2C_neuroimmunology%2C_immunology%2C_multiple_sclerosis%2C_Neurobiology%2C_Neuroscience%2C_Translational_Medicine%2C_Molecular_Medicine_%26_Human_Disease%2C_Immunology> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/2004/02/skos/core#Concept> .
                <http://sul.stanford.edu/rialto/context/positions/capFaculty_Child_Health_Research_Institute_3784> <http://vivoweb.org/ontology/core#hrJobTitle> "George A. Zimmermann Professor and Professor of Pediatrics" . } }
       WHERE {  }
```

The message in Cloudwatch logs:

```
16:46:43 START RequestId: 782fb063-9c2e-11e8-9ba2-9bed680c4a32 Version: $LATEST
16:46:43 2018/08/09 23:44:40 AFTER NEPTUNE: [
16:46:43 {
16:46:43 "type" : "UpdateEvent",
16:46:43 "totalElapsedMillis" : 26,
16:46:43 "elapsedMillis" : 24,
16:46:43 "connFlush" : 0,
16:46:43 "batchResolve" : 0,
16:46:43 "whereClause" : 11,
16:46:43 "deleteClause" : 0,
16:46:43 "insertClause" : 12
16:46:43 },
16:46:43 {
16:46:43 "type" : "Commit",
16:46:43 "totalElapsedMillis" : 36
16:46:43 }
16:46:43 ]
16:46:43 2018/08/09 23:46:43 BEFORE NEPTUNE: {0xc4200be780}
16:46:43 2018/08/09 23:46:43 AFTER NEPTUNE: [
16:46:43 {
16:46:43 "type" : "UpdateEvent",
16:46:43 "totalElapsedMillis" : 27,
16:46:43 "elapsedMillis" : 26,
16:46:43 "connFlush" : 0,
16:46:43 "batchResolve" : 0,
16:46:43 "whereClause" : 12,
16:46:43 "deleteClause" : 0,
16:46:43 "insertClause" : 13
16:46:43 },
16:46:43 {
16:46:43 "type" : "Commit",
16:46:43 "totalElapsedMillis" : 35
16:46:43 }
16:46:43 ]
16:46:43 END RequestId: 782fb063-9c2e-11e8-9ba2-9bed680c4a32
16:46:43 REPORT RequestId: 782fb063-9c2e-11e8-9ba2-9bed680c4a32	Duration: 136.05 ms	Billed Duration: 200 ms Memory Size: 128 MB	Max Memory Used: 38 MB
```

### PR DESCRIPTION
**Pull request by aaron-collier**
Closes #11 and closes #12

### CODE REVIEW

**Comment by tingulfsen** [comment]
@aaron-collier  does this actually **fix** those two issues or not?

https://help.github.com/articles/closing-issues-using-keywords/

**Comment by aaron-collier** [comment]
@tingulfsen I believe it does, thanks for the TIP :-)

File: sparql/parse.go [hunk 1]
```diff
@@ -102,6 +110,9 @@ func (query *Query) Parse(src io.Reader) error {
 					verb = ""
 				}
 			} else {
+				if namedGraph && query.NamedGraph == "" {
+					query.NamedGraph = string(b[uriStart+1 : s.Position.Offset])
+				}
```
Comment (tingulfsen) [inline sparql/parse.go]: This function is getting to be fairly long. What do you think about breaking it up? If time is of the essence, I'd also be happy to create a refactoring ticket.

Comment (aaron-collier) [reply sparql/parse.go]: Yeah, this is getting a bit long and I think needs cleanup. I mostly wanted to capture the current state here but can continue to clean it up.

File: sparql/sparql.go [hunk 2]
```diff
@@ -9,8 +9,9 @@ type Sparql struct {
 
 // Query is a struct to hold a full SPARQL query
 type Query struct {
-	Parts    []Sparql
-	Prefixes map[string]string
+	Parts      []Sparql
+	Prefixes   map[string]string
+	NamedGraph string
```
Comment (jcoyne) [inline sparql/sparql.go]: Could this be `*string` so that it would permit a NULL value rather than `""`?

Comment (aaron-collier) [reply sparql/sparql.go]: Sure.
